### ISSUE TITLE
problem set 2 

### ISSUE THREAD

**Issue by chrismit258** [MOLB7950/Discussion#39]
I am having trouble submitting problem set 2. Every time I type a "git" command, I get this error: 
fatal: Not a git repository (or any parent up to mount point /vol2)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

I needed to use SSH to upload my prob set 1 answers, so I am wondering if it has something to do with that?

**Comment by jayhesselberth** [comment]
I doesn't look like the repo you have is a git repo.

My suggestion is to:

1. clone a fresh repo somewhere else (e.g. in $HOME/tmp).
1. Copy the files from your original repo into the new one (e.g. `cp answers.sh ...`)
1. Move to the new repo and add the new files (`git add file1 file2`).
1. Then commit / push like you have been doing.

**Comment by chrismit258** [comment]
@jayhesselberth I did as you said, and now when I try to type git commit I get this error: 
error: pathspec 'answers.sh' did not match any file(s) known to git.
error: pathspec 'answers.yml' did not match any file(s) known to git.

and when I try to type git push I get this error: 
error: src refspec answers.yml does not match any.
error: failed to push some refs to 'answers.sh'

**Comment by jayhesselberth** [comment]
I logged into your account on tesla and added / committed the files:

```bash
# in ~/moveable/problem-set-2
$ git add answers.sh answers.yml run.sh
$ git commit -m 'add new files' .
```

You just need to go into that directory, run `git push` and enter credentials, and then submit a pull request from github.com.

**Comment by chrismit258** [comment]
Thanks. I just submitted.

**Comment by anndoan** [comment]
Please advise on how to fix the following problem.  When typing git commit - I got the this error:

anndoan@compute04 ~/problem-set-2
$ git commit -m "problem set 2" answers.sh answers.yml
On branch master
Your branch is ahead of 'origin/master' by 2 commits.
  (use "git push" to publish your local commits)
Untracked files:
        question2.bed
        run.sh

nothing added to commit but untracked files present

**Comment by jayhesselberth** [comment]
Run `git push` to push your committed changes to github.

**Comment by anndoan** [comment]
I got another error when typed "git push". 

"anndoan@amc-tesla ~/problem-set-2 [1]
$ git push
warning: push.default is unset; its implicit value has changed in
Git 2.0 from 'matching' to 'simple'. To squelch this message
and maintain the traditional behavior, use:

  git config --global push.default matching

To squelch this message and adopt the new behavior now, use:

  git config --global push.default simple

When push.default is set to 'matching', git will push local branches
to the remote branches that already exist with the same name.

Since Git 2.0, Git defaults to the more conservative 'simple'
behavior, which only pushes the current branch to the corresponding
remote branch that 'git pull' uses to update the current branch.

See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
'current' instead of 'simple' if you sometimes use older versions of Git)


(gnome-ssh-askpass:31920): Gtk-WARNING **: cannot open display:
error: unable to read askpass response from '/usr/libexec/openssh/gnome-ssh-askpass'
Username for 'https://github.com': anndoan

(gnome-ssh-askpass:32317): Gtk-WARNING **: cannot open display:
error: unable to read askpass response from '/usr/libexec/openssh/gnome-ssh-askpass'
Password for 'https://anndoan@github.com':
remote: Permission to MOLB7621/problem-set-2.git denied to anndoan.
fatal: unable to access 'https://github.com/MOLB7621/problem-set-2.git/': The requested URL returned error: 403"

**Comment by kriemo** [comment]
@anndoan It looks you cloned the `problem-set-2` repo from the MOLB7621 repo instead of from a forked version. 

To fix this do the following:

1)  Fork the problem-set-2 repo on github
2) `git clone` your forked repository using the ssh option (i.e. `git@github.com:anndoan/problem-set-2/`) to a new directory. 

Then Follow Jay's advice above:

3) Copy the files from your original repo into the new one (e.g. cp answers.sh ...)
4) Move to the new repo and add the new files (git add file1 file2).
5) Then commit / push like you have been doing.

Also make sure that you run `qlogin` prior to using `git`. Your prompt should look different after you run `qlogin`. 

```bash
anndoan@amc-tesla ~ #before running qlogin
qlogin
anndoan@compute-XX ~ #after running qlogin (xx = a number beween 00-16) 
```
